<b>Key Feature:</b> It's N-dimensional array object, or ndarray, which is fast, flexible containers for large data sets in Python.
<br>
** Arrays enable to perform mathematical operation on whole blocks of data using similar syntax to the equivalent operations between scaler elements

In [1]:
import numpy as np

In [2]:
data = np.array([[0.9526, -0.246, -0.8856], [0.5639, 0.2379, 0.9104]])

In [3]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [4]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [9]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data)
arr1

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
# Checking data type
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
# Functions for creating new arrays
# zeros and ones create arrays of 0's and 1's with given length or shape.
# empty creates an array without initializing its value to any particular value
# to create a heigher dimensional array with these methods, pass a tuple for the shape
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
# It's not safe to assume that np.empty will remain an array of all zeros.
# In many cases it will return uninitialized garbage values
np.empty((2, 3, 2))

array([[[1.38521121e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 1.61590357e+184]],

       [[7.79198733e-091, 9.90700532e+164],
        [1.55054934e+184, 2.59792841e-056],
        [3.99910963e+252, 4.93432906e+257]]])

In [23]:
# array is an array-valued version to built-in Python range function
np.array(15)

array(15)

### Data Types for ndarray

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [25]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
# Explicitly convert or cast an array from one dtype to another using ndarray's astype method
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [30]:
# Cast floating number to be integer dtype, the decimal part will be turncated
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

### Operations between Arrays and Scalers
<br>
Array are important because they enable to express batch operations on data without wirting any for loops. This usually called <b>Vectorization</b>. Any arithmetic operations between equal-size arrays applies the operation elementwise

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [33]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# Arithmetic operations with scalers are, propagating the value to each elements
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Basic Indexing and Slicing

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5]

5

In [43]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[5:8] = 12

In [45]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [46]:
# An important first distinction from list is that array slices are views on the original array
# This means that the data is not copied, and any modification to the view will be reflected in the source array.
arr_slice = arr[5:8]

In [47]:
arr_slice[1] = 12345

In [48]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [51]:
arr_slice[:] = 74

In [52]:
arr

array([64, 64, 64, 64, 64, 74, 74, 74, 64, 64])

In [54]:
# As NumPy has been designed with large data use cases in mind, we could imagine performance and memory problems if NumPy 
# insisted on copying data left and right

# If want a copy of slice of an ndarry instead of a view, we need to explicitly copy the array; exmaple arr[5:8].copy()
# Indexing with slices - Higher dimensional objects gice more options for slicing, as we can slice one or more axes and also
# mix integers. For exmple in 2D array

### Boolean Indexning

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [60]:
data = np.random.rand(7, 4)

In [61]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data

array([[0.89501714, 0.24650966, 0.69863783, 0.89818627],
       [0.73365612, 0.30281363, 0.24729851, 0.49488393],
       [0.4498052 , 0.84051304, 0.53876766, 0.31680282],
       [0.39951984, 0.68950846, 0.0366825 , 0.12077309],
       [0.82908635, 0.2261225 , 0.64554041, 0.8496998 ],
       [0.60465412, 0.87658687, 0.05832543, 0.81105468],
       [0.39031654, 0.30067321, 0.1648703 , 0.02860712]])

In [64]:
# Suppose each name corresponds to a row in data array.
names == "Bob" # Boolean Array

array([ True, False, False,  True, False, False, False])

In [66]:
# This boolean array can be passed when indexing the array
data[names == "Bob"]

array([[0.89501714, 0.24650966, 0.69863783, 0.89818627],
       [0.39951984, 0.68950846, 0.0366825 , 0.12077309]])

In [67]:
data[names == "Bob", 2:]

array([[0.69863783, 0.89818627],
       [0.0366825 , 0.12077309]])

In [68]:
data[names == "Bob", 3]

array([0.89818627, 0.12077309])

In [71]:
# Select everything except Bob
data[names != "Bob"]

array([[0.73365612, 0.30281363, 0.24729851, 0.49488393],
       [0.4498052 , 0.84051304, 0.53876766, 0.31680282],
       [0.82908635, 0.2261225 , 0.64554041, 0.8496998 ],
       [0.60465412, 0.87658687, 0.05832543, 0.81105468],
       [0.39031654, 0.30067321, 0.1648703 , 0.02860712]])

In [74]:
data[data < 0.6] = 0

In [75]:
data

array([[0.89501714, 0.        , 0.69863783, 0.89818627],
       [0.73365612, 0.        , 0.        , 0.        ],
       [0.        , 0.84051304, 0.        , 0.        ],
       [0.        , 0.68950846, 0.        , 0.        ],
       [0.82908635, 0.        , 0.64554041, 0.8496998 ],
       [0.60465412, 0.87658687, 0.        , 0.81105468],
       [0.        , 0.        , 0.        , 0.        ]])

In [76]:
data[names != 'Joe'] = 7

In [77]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.73365612, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.60465412, 0.87658687, 0.        , 0.81105468],
       [0.        , 0.        , 0.        , 0.        ]])

### Fancy Index
<br>
Fancy indexing is termed adopted by NumPy to descibe indexing using integers arrays

In [78]:
arr = np.empty((8, 4))

In [79]:
for i in range(8):
    arr[i] = i

In [80]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
# Select out a subset of the rows in a particular order - simply pass a list or ndarray of integers specify the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [82]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [85]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [86]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])